### ISSUE TITLE
Can't create new Note

### ISSUE THREAD

**Issue by lazyjinchuriki** [Electromorphous/DeNotes#5]
![Screenshot_20231007_143113_Soul](https://github.com/Electromorphous/DeNotes/assets/92175633/a88d5fe9-8cce-471b-9896-e9fd9eba83a5)

**Comment by Electromorphous** [comment]
Please be more descriptive. From everywhere I have tested, I can create a new note.

**Comment by lazyjinchuriki** [comment]
In your deployed site, it is taking too much time to create.
P.S. my internet connection is good.

**Comment by Electromorphous** [comment]
Yeah the first few times it will take a bit to create a new note. Also you can take a look at the source code, there is no other process happening other than uploading the data to the IPFS. That's the only operation which takes time. 

I am planning on creating an implementation of the IPFS node instead of continuing to use ThirdWeb at some point in the future after all the other more important features have been created, hopefully we will have more control on this connection that way.

Meanwhile if you do find a way to speed up this process - either using the thirdweb library or by creating an IPFS node manually, feel free to make a PR for it.

If that answers your question we can go ahead and close this issue.
